version: '3'

services:

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysqlq
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress1
    ports: 
      - 3307:3306
  php:
    image: wordpress:5.7
    ports:
      - "8080:80"
    volumes: 
      - ../:/var/www/html
    links: 
      - db:mysql
    depends_on: 
      - db

    
volumes:
    db_data: {}